version: '3'
services:
  nginx:
    image: nginx:1.21.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - "./nginx/conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/html:/usr/share/nginx/html"
      - "./nginx/log:/var/log/nginx"
    ports:
      - "8011:80"